/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAR-COUNT_H_RPCGEN
#define _CHAR-COUNT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct string_in {
	char *in_string;
	char in_char;
};
typedef struct string_in string_in;

struct count_out {
	long count;
};
typedef struct count_out count_out;

#define CHARACTERCOUNT_PROG 0x31203923
#define CHARACTERCOUNT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getCharacterCount 1
extern  count_out * getcharactercount_1(string_in *, CLIENT *);
extern  count_out * getcharactercount_1_svc(string_in *, struct svc_req *);
extern int charactercount_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getCharacterCount 1
extern  count_out * getcharactercount_1();
extern  count_out * getcharactercount_1_svc();
extern int charactercount_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_string_in (XDR *, string_in*);
extern  bool_t xdr_count_out (XDR *, count_out*);

#else /* K&R C */
extern bool_t xdr_string_in ();
extern bool_t xdr_count_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAR-COUNT_H_RPCGEN */
