/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "char-count.h"


int
main (int argc, char *argv[])
{
	if (argc != 4) {
		printf ("usage: %s <server> <input string> <character>\n", argv[0]);
		exit (1);
	}
    
	CLIENT *clnt;
	count_out  *result_1;
	string_in  getcharactercount_1_arg;

    getcharactercount_1_arg.in_char = argv[3][0]; 
    getcharactercount_1_arg.in_string = argv[2];


	clnt = clnt_create (argv[1], CHARACTERCOUNT_PROG, CHARACTERCOUNT_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (argv[1]);
		exit (1);
	}


	result_1 = getcharactercount_1(&getcharactercount_1_arg, clnt);
	if (result_1 == (count_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}

    printf("# of occurences of %c in %s = %ld\n",argv[3][0], argv[2],
            result_1->count);

    clnt_destroy (clnt);
    exit (0);
}
