/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "char-count.h"

#include <string.h>

count_out *
getcharactercount_1_svc(string_in *argp, struct svc_req *rqstp)
{
	static count_out  result;

    result.count = 0;
    int i = 0;
    char *str = argp->in_string;

    while(str[i] != 0){
        if(str[i] == argp->in_char){
            result.count += 1;
        }
        ++i;
    }

	return &result;
}
